Replaces conda with mamba

diff --git a/bin/equip b/bin/equip
--- a/bin/equip
+++ b/bin/equip
@@ -41,7 +41,7 @@ CODE_PACKAGES="                                                                \
     richie5um2.vscode-sort-json streetsidesoftware.code-spell-checker          \
     sysoev.language-stylus timonwong.shellcheck"
 
-CONDA_PACKAGES="                                                               \
+MAMBA_PACKAGES="                                                               \
     appdirs appnope attrs backcall brotlipy ca-certificates cachecontrol cachy \
     certifi cffi charset-normalizer cleo clikit crashtest cryptography         \
     decorator distlib filelock html5lib idna importlib-metadata                \
@@ -67,7 +67,7 @@ CARGO_PACKAGES="                                                               \
     cargo-update jless loc porsmo"
 # END GENERATED PACKAGE LISTS
 
-ITEM_LISTS=(HOMEBREW_FORMULAS HOMEBREW_CASKS CODE_PACKAGES CONDA_PACKAGES
+ITEM_LISTS=(HOMEBREW_FORMULAS HOMEBREW_CASKS CODE_PACKAGES MAMBA_PACKAGES
     NODE_MODULES GO_PACKAGES CARGO_PACKAGES)
 
 # Speeds things up when running homebrew commands
@@ -177,24 +177,13 @@ array_contains() {
     return $in
 }
 
-ensure_no_anaconda() {
-    # Anaconda is known to frequently break Homebrew builds, including Vim and
+ensure_no_mamba() {
+    # Mamba is known to frequently break Homebrew builds, including Vim and
     # MacVim, due to bundling many duplicates of system and Homebrew-available
     # tools. Make sure to exit it before doing anything with Homebrew.
-
-    if [[ -n $CONDA_DEFAULT_ENV ]]; then
-        if command -v deactivate >/dev/null 2>&1; then
-            run "conda deactivate"
-        fi
+    if [[ -n $CONDA_PREFIX ]]; then
+        run "micromamba deactivate"
     fi
-
-    if [[ -n $ANACONDA_ROOT ]]; then
-        PATH="$(echo "$PATH" | sed "s@$ANACONDA_ROOT/bin@@g;s@::@:@g;s@^:@@;s@:\$@@;")"
-        MANPATH="$(echo "$PATH" | sed "s@$ANACONDA_ROOT/share/man@@g;s@::@:@g;s@^:@@;s@:\$@@;")"
-        export PATH
-        export MANPATH
-    fi
-    unset PYTHON_ENV
 }
 
 # Usage: in_array "$element" "${array[@]}"
@@ -1036,7 +1025,7 @@ ensure_homebrew_updated() {
         abort "Please run step brew first"
     fi
 
-    ensure_no_anaconda
+    ensure_no_mamba
 
     # unlink keg-only formulas which should not be not symlinked into brew path
     KEG_ONLY=(gettext libffi libtool openssl readline sqlite)
@@ -1077,7 +1066,7 @@ install_brew_formula() {
 }
 
 step_brew() {
-    ensure_no_anaconda
+    ensure_no_mamba
 
     if [[ -z "$(command -v brew)" ]]; then
         show "installing homebrew..."
@@ -1207,7 +1196,7 @@ step_cask() {
     for I in $(brew ls --cask -1); do
         name="${I%@*}"
         if ! echo "$HOMEBREW_CASKS" | grep -Eq "$(echo "\\b$name\\b" | sed 's/ (!)//g')"; then
-            if [[ $I != "miniconda" ]]; then
+            if [[ $I != "micromamba" ]]; then
                 show -i "$I installed but not managed by equip via brew cask"
             fi
         fi
@@ -1317,60 +1306,33 @@ step_bash() {
 # Step python
 ################################################################################
 step_python() {
-    local ANACONDA_DIR_NAME="/usr/local/Caskroom/miniconda/base"
-
-    # enter existing anaconda environment if it's detected
-    [[ -d "$ANACONDA_DIR_NAME/bin" ]] && export PATH="$ANACONDA_DIR_NAME/bin:$PATH"
-
-    if run "command -v conda >/dev/null 2>&1"; then
-        MANAGE_WITH_ANACONDA=0
-        if [[ $MANAGE_WITH_ANACONDA == 1 ]]; then
-            # Allow anaconda to manage all the packages we've installed so that we're reasonably
-            # sure that the installed versions will play nicely with each other.
-            run "conda update --yes --prefix '$ANACONDA_DIR_NAME' conda"
-        else
-            # Remove anaconda so that `conda update --all` doesn't stupidly downgrade things.
-            # See https://github.com/conda/conda/issues/463 for more details.
-            run "conda remove --yes anaconda"
-            # Ensures that we get the latest versions possible of installed packages.
-            # Though we risk those versions maybe not playing well with each other.
-            run "conda update --yes -n base conda"
-            run "conda update --yes --prefix '$ANACONDA_DIR_NAME' --all"
-        fi
+    if run "command -v micromamba >/dev/null 2>&1"; then
+        show "micromamba already installed"
     else
         ensure_homebrew_updated
-        install_brew_cask miniconda
+        install_brew_cask micromamba || abort "Can't install micromamba via brew-cask"
         ensure_homebrew_updated_cleanup
-        export PATH="$ANACONDA_DIR_NAME/bin:$PATH"
-        run "conda config --set changeps1 no"
     fi
 
-    # Remove terrible Anaconda launcher apps from desktop (That's not where .app directories go anyway!)
-    [[ -d "$HOME/Desktop/Launcher.app" ]] && run "rm -rf '$HOME/Desktop/Launcher.app'"
-    [[ -d "$HOME/Desktop/Navigator.app" ]] && run "rm -rf '$HOME/Desktop/Navigator.app'"
+    if [[ -z $CONDA_PREFIX ]]; then
+        run "micromamba activate"
+    fi
 
-    # Install conda packages that don't come pre-installed with Anaconda
-    local CONDA_LIST
-    CONDA_LIST="$(conda list -e | cut -f1 -d= | grep -Ev '^#|^_|anaconda|^conda|^python$|^python.app$')"
+    # Install mamba packages that don't come pre-installed with micromamba
+    local MAMBA_LIST
+    MAMBA_LIST="$(micromamba list --json | jq -r '.[].name' | grep -Ev '^python$')"
     IFS=' '
-    for I in $CONDA_PACKAGES; do
-        if ! echo "$CONDA_LIST" | grep -q "$I"; then
-            run "conda install -f --yes $I"
+    for I in $MAMBA_PACKAGES; do
+        if ! echo "$MAMBA_LIST" | grep -q "$I"; then
+            run "micromamba install -q -c conda-forge --yes $I"
         fi
     done
 
-    # Fix annoying ipython settings
-    if command -v ipython >/dev/null 2>&1; then
-        run "ipython profile create"
-        run "perl -pi -e 's/.*confirm_exit.*/c.TerminalInteractiveShell.confirm_exit = False/' $HOME/.ipython/profile_default/ipython_config.py"
-        run "perl -pi -e 's/.*display_banner.*/c.TerminalIPythonApp.display_banner = False/' $HOME/.ipython/profile_default/ipython_config.py"
-    fi
-
     IFS=$'\n'
-    for I in $CONDA_LIST; do
+    for I in $MAMBA_LIST; do
         name="${I%@*}"
-        if ! echo "$CONDA_PACKAGES" | grep -Eq "\\b$name\\b"; then
-            show -i "$I installed but not managed by equip via conda"
+        if ! echo "$MAMBA_PACKAGES" | grep -Eq "\\b$name\\b"; then
+            show -i "$I installed but not managed by equip via micromamba"
         fi
     done
 }
@@ -1661,7 +1623,7 @@ steps=(
     "ext;           Ensure file extension associations are correct"
     "zsh;           Ensure shell is latest version of zsh from Homebrew"
     "env;           Update environment configuration and submodules"
-    "python;        Upgrade/Install python and conda packages"
+    "python;        Upgrade/Install python and mamba packages"
     "node;          Ensure Node modules are installed via npm"
     "go;            Ensure Go packages are installed"
     "cargo;         Ensure Rust packages are installed via cargo"
