Remove junk software rvm, install not as bad junk
The asdf utility is slightly less shitty than rvm.

- Adds asdfrc and root level tool-versions config.
- Strips rvm junk out of everywhere.

diff --git a/bin/equip b/bin/equip
--- a/bin/equip
+++ b/bin/equip
@@ -7,7 +7,7 @@
 ################################################################################
 # BEGIN GENERATED PACKAGE LISTS
 HOMEBREW_FORMULAS="                                                            \
-    adns aom autoconf automake avro-c bash bat cairo clang-format cmake        \
+    adns aom asdf autoconf automake avro-c bash bat cairo clang-format cmake   \
     colordiff coreutils csv-fix diff-so-fancy docker doxygen duti entr exa     \
     exiftool expect faac fasd ffmpeg flac flake8 fontconfig freetype frei0r    \
     fribidi fzf gd gdbm geoip gettext ghostscript giflib gifsicle git git-flow \
@@ -1464,40 +1464,40 @@ step_python() {
 ################################################################################
 # Step gem
 ################################################################################
-ensure_rvm_ruby() {
-    if command -v ruby | grep -q "/usr/bin/ruby"; then
-        if [[ ! -e "$HOME/.rvm/scripts/rvm" ]]; then
-            run "command curl -sSL https://rvm.io/mpapis.asc | gpg --import -"
-            run "command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -"
-            run '\curl -sSL https://get.rvm.io | bash -s stable --ruby' || abort "Failed to install rvm"
-        fi
-        if ! command -v rvm >/dev/null 2>&1; then
-            # shellcheck source=.rvm/scripts/rvm
-            # shellcheck disable=SC1091
-            test -s "$HOME/.rvm/scripts/rvm" && source "$_"
-        fi
-        if [[ -z "$(rvm list strings)" ]]; then
-            run "rvm install ruby --latest" || abort "Could not install ruby via rvm"
-            run "rvm alias create default '$(rvm list strings)'"
-        fi
+ensure_asdf_ruby() {
+    # update or install asdf ruby plugin
+    if asdf plugin-list | grep -q ruby; then
+        run "asdf plugin update --all"
+    else
+        run "asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git" || abort "failed to install asdf ruby plugin"
     fi
 
-    if ! command -v rvm >/dev/null 2>&1; then
-        abort "rvm not installed"
-    fi
-    run "rvm get head" || abort "Could not update rvm"
+    # ensure asdf is set up correctly for this shell
+    # shellcheck disable=SC1090
+    source "$(brew --prefix asdf)/asdf.sh"
 
-    # shellcheck source=.rvm/scripts/rvm
-    # shellcheck disable=SC1091
-    test -s "$HOME/.rvm/scripts/rvm" && source "$_"
-    run "rvm use '$(rvm list default string)'" || abort "Could not select default ruby via rvm"
+    if [[ -z "$(asdf list ruby 2>/dev/null)" ]]; then
+        if ! brew list --formula | grep -q readline; then
+            abort "Please run step brew first, readline not installed via brew"
+        fi
+
+        if ! brew list --formula | grep -q openssl; then
+            abort "Please run step brew first, openssl not installed via brew"
+        fi
+
+        # workaround issue where ruby won't compile unless you tell it where openssl lives
+        # see https://github.com/rbenv/ruby-build/issues/1409 for more details
+        # shellcheck disable=SC2155
+        export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl)"
+
+        run "asdf install ruby latest" || abort "failed to install latest version of ruby via asdf"
+    fi
 }
 
 step_gem() {
-    ensure_rvm_ruby
-    if command -v ruby | grep -q "/usr/bin/ruby"; then
-        abort "System ruby detected, please ensure ruby installed via rvm"
-    fi
+    ensure_homebrew_updated
+    ensure_asdf_ruby
+    ensure_homebrew_updated_cleanup
 
     show "Note that some gems have dependencies that should be installed by brew first..."
     run "yes | gem install rubygems-update"
