Adds .shell_control and updates many scripts to use it.

diff --git a/bin/git_push_topic b/bin/git_push_topic
--- a/bin/git_push_topic
+++ b/bin/git_push_topic
@@ -2,16 +2,7 @@
 
 # Force updates remote topic branch with local branch.
 
-function show()
-{
-	echo $'\e[1;34m==>\e[0m\e[31m' "$1" $'\e[0m'
-}
-
-function abort()
-{
-	echo $'\e[1;31merror:' "$1" $'\e[0m' >&2
-	exit 1
-}
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
 
 BRANCH="$(git rev-parse --abbrev-ref HEAD)"
 [[ "$BRANCH" != "master" ]] || abort "$BRANCH isn't a topic branch, dummy!"
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,12 +2,15 @@
 
 # Installs everything to ~/bin.
 
-mkdir -p ~/bin
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
+
+run "mkdir -p '$HOME/bin'"
 
 for I in *; do
-	if [[ "$I" != "install" && "$I" != "update_bin" && "$I" != "usages" ]]; then
-		rsync -avl $I ~/bin/$I
-	fi
+	case "$I" in
+		*) run "rsync -apl '$I' '$HOME/bin/$I'" ;;
+		install|update_bin|usages|ignore) ;; # don't install these files
+	esac
 done
 
-echo "~/bin install complete!"
+show "$HOME/bin install complete!"
diff --git a/bin/install_atom b/bin/install_atom
--- a/bin/install_atom
+++ b/bin/install_atom
@@ -19,35 +19,12 @@ ATOM_PACKAGES="
     linter-shellcheck
 "
 
-function show()
-{
-    echo $'\e[1;34m==>\e[0m\e[31m' "$1" $'\e[0m'
-}
-
-function run()
-{
-    show "$1"
-    eval "$1"
-    return $?
-}
-
-function abort()
-{
-    echo $'\e[1;31merror:' "$1" $'\e[0m' >&2
-    exit 1
-}
-
-function ask()
-{
-    echo -n $'\n\e[1;35m'
-    read -p "$1 (y/n) [n] ... "
-    echo -n $'\e[0;0m'
-}
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
 
 # Install Atom
 ATOM_ZIP="/tmp/atom.zip"
 
-function unzip_atom_into_applications()
+unzip_atom_into_applications()
 {
     run "wget -c 'https://atom.io/download/mac' -O $ATOM_ZIP" || abort "can't download Atom"
     run "unzip /tmp/atom.zip -d /Applications 1>/dev/null" || abort "can't install Atom"
@@ -81,7 +58,7 @@ EOF
 fi
 
 # Install desired Atom packages
-function install_pkg()
+install_pkg()
 {
     local PKG="$1"
     local INSTALLED="$(apm list --installed --bare | grep "$PKG")"
diff --git a/bin/install_dev b/bin/install_dev
--- a/bin/install_dev
+++ b/bin/install_dev
@@ -27,7 +27,7 @@ GEM_PACKAGES="cap_gun archive-tar-minitar bson bson_ext bundler bundler-unload  
 ################################################################################
 # Utilities
 ################################################################################
-function usage()
+usage()
 {
     echo "usage: $(basename "$0") [-l | all | step-name ]"
     echo "options:"
@@ -40,46 +40,12 @@ function usage()
     exit 0
 }
 
-function show()
-{
-    echo $'\e[1;34m==>\e[0m\e[31m' "$1" $'\e[0m'
-}
-
-function run()
-{
-    show "$1"
-    if [[ $DRYRUN == 0 ]]; then
-        eval "$1"
-        return $?
-    else
-        return 0
-    fi
-}
-
-function abort()
-{
-    if [[ -n "$2" ]]; then
-        run "$2"
-    fi
-    echo $'\e[1;31merror:' "$1" $'\e[0m' >&2
-    exit 1
-}
-
-function ask()
-{
-    if [[ $FORCE = 1 ]]; then
-        REPLY='y'
-        return 0
-    fi
-    echo -n $'\n\e[1;35m'
-    read -p "$1 (y/n) [n] ... "
-    echo -n $'\e[0;0m'
-}
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
 
 ################################################################################
 # Steps
 ################################################################################
-function step_setup_xcode() # xcode
+step_setup_xcode() # xcode
 {
     export SELECT="select"
     if [[ -z "$(which xcode-$SELECT)" ]]; then
@@ -94,13 +60,13 @@ function step_setup_xcode() # xcode
     show "Xcode Command Line Tools properly installed."
 }
 
-function step_check_java() # java
+step_check_java() # java
 {
     show "Checking if java's installed..."
     run "java -version"
 }
 
-function step_check_homebrew() # checkbrew
+step_check_homebrew() # checkbrew
 {
     diff <(echo "$HOMEBREW_FORMULAS" \
         | sort -u \
@@ -113,7 +79,7 @@ function step_check_homebrew() # checkbrew
             # we expect openssl, readline, and sqlite to be unlinked
 }
 
-function install_brew_formula()
+install_brew_formula()
 {
     if [[ -z "$(brew ls | grep "$1")" ]]; then
         run "brew install $1"
@@ -125,7 +91,7 @@ function install_brew_formula()
     run "brew unlink $1 && brew link --force --overwrite $1"
 }
 
-function ensure_homebrew_updated()
+ensure_homebrew_updated()
 {
     if [[ -z "$(which brew)" ]]; then
         abort "please install Homebrew first"
@@ -135,7 +101,7 @@ function ensure_homebrew_updated()
     run "brew upgrade"
 }
 
-function step_install_homebrew() # brew
+step_install_homebrew() # brew
 {
     if [[ -z "$(which brew)" ]]; then
         show "installing homebrew..."
@@ -171,7 +137,7 @@ function step_install_homebrew() # brew
     run "brew unlink openssl readline sqlite"
 }
 
-function step_install_python() # python
+step_install_python() # python
 {
     # enter existing anaconda environment if it's detected
     [[ -d "$HOME/anaconda/bin" ]] && export PATH="$HOME/anaconda/bin:$PATH"
@@ -220,7 +186,7 @@ function step_install_python() # python
     run "perl -pi -e 's/.*display_banner.*/c.TerminalIPythonApp.display_banner = False/' $HOME/.ipython/profile_default/ipython_config.py"
 }
 
-function step_install_gem() # gem
+step_install_gem() # gem
 {
     run "yes | sudo gem install rubygems-update"
     run "yes | sudo update_rubygems"
@@ -235,7 +201,7 @@ function step_install_gem() # gem
     done
 }
 
-function step_install_xquartz() # xquartz
+step_install_xquartz() # xquartz
 {
     if type Xquartz >/dev/null 2>&1; then
         show "a Xquartz is already installed..."
@@ -266,7 +232,7 @@ function step_install_xquartz() # xquartz
     run "$cleanup"
 }
 
-function ensure_install_shell()
+ensure_install_shell()
 {
     local BINARY="$1"
     local INSTALLED="$(grep "$BINARY" /etc/shells)"
@@ -275,7 +241,7 @@ function ensure_install_shell()
     fi
 }
 
-function step_install_bash() # bash
+step_install_bash() # bash
 {
     ensure_homebrew_updated
     install_brew_formula bash
@@ -288,7 +254,7 @@ function step_install_bash() # bash
     run "chsh -s \"$HB_BASH_BINARY\" \"$(whoami)\""
 }
 
-function step_install_zsh() # zsh
+step_install_zsh() # zsh
 {
     ensure_homebrew_updated
     install_brew_formula zsh
@@ -302,7 +268,7 @@ function step_install_zsh() # zsh
     run "chsh -s \"$HB_ZSH_BINARY\" \"$(whoami)\""
 }
 
-function step_install_tiddlywiki() # tiddlywiki
+step_install_tiddlywiki() # tiddlywiki
 {
     ensure_homebrew_updated
     install_brew_formula node
@@ -373,6 +339,10 @@ while getopts "hlfd" opt; do
     esac
 done
 shift $((OPTIND - 1))
+
+# export force/dryrun settings to shell control variables (see ~/.shell_control)
+export SC_FORCE="$FORCE"
+export SC_DRYRUN="$DRYRUN"
 
 if [[ $LISTING == 0 && -z "$1" ]]; then
     usage
diff --git a/bin/nopw b/bin/nopw
--- a/bin/nopw
+++ b/bin/nopw
@@ -7,10 +7,7 @@ if [[ -z "$1" ]]; then
 	exit 1
 fi
 
-function show()
-{
-	echo -e $'\e[1;34m' "$1" $'\e[0m'
-}
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
 
 KEY_TYPE="${KEY_TYPE:-rsa}"
 KEY="${KEY:-id_$KEY_TYPE}"
@@ -20,7 +17,7 @@ show "*** KEY_TYPE set to ${KEY_TYPE} ***"
 show "*** KEY set to ${KEY} ***"
 echo
 
-function local_run()
+run_local()
 {
 	echo $'\e[1;34mlocal ==>\e[0m\e[31m' "$1" $'\e[0m'
 	eval "$1"
@@ -29,27 +26,27 @@ function local_run()
 
 set -e
 
-[[ -d "$HOME/.ssh" ]] || local_run "mkdir -p '$HOME/.ssh'"
-[[ -f "$HOME/.ssh/authorized_keys" ]] || local_run "touch '$HOME/.ssh/authorized_keys'"
+[[ -d "$HOME/.ssh" ]] || run_local "mkdir -p '$HOME/.ssh'"
+[[ -f "$HOME/.ssh/authorized_keys" ]] || run_local "touch '$HOME/.ssh/authorized_keys'"
 
 if [[ ! -f "$HOME/.ssh/$KEY.pub" ]]; then
-	local_run "ssh-keygen -t '$KEY_TYPE'"
-	local_run "cat '$HOME/.ssh/$KEY.pub' >> '$HOME/.ssh/authorized_keys'"
+	run_local "ssh-keygen -t '$KEY_TYPE'"
+	run_local "cat '$HOME/.ssh/$KEY.pub' >> '$HOME/.ssh/authorized_keys'"
 fi
 
 # SSH requires certain permissions on home directory, .ssh directory, and authorized_keys file
-local_run "chmod go-w $HOME"
-local_run "chmod go-rwx $HOME/.ssh"
-local_run "chmod go-rwx $HOME/.ssh/authorized_keys"
+run_local "chmod go-w $HOME"
+run_local "chmod go-rwx $HOME/.ssh"
+run_local "chmod go-rwx $HOME/.ssh/authorized_keys"
 
 echo
 show "*** You will be asked for your password twice... ***"
 echo
 
-local_run "cat '$HOME/.ssh/$KEY.pub' | ssh $@ 'cat > \"$KEY.pub\"'"
+run_local "cat '$HOME/.ssh/$KEY.pub' | ssh $@ 'cat > \"$KEY.pub\"'"
 
 ssh "$@" "bash -s" << EOF
-	function remote_run()
+	remote_run()
 	{
 		echo $'\e[1;34mremote ==>\e[0m\e[31m' "\$1" $'\e[0m'
 		eval "\$1"
diff --git a/bin/s b/bin/s
--- a/bin/s
+++ b/bin/s
@@ -2,26 +2,7 @@
 
 # Show git status for all directories in current directory.
 
-function show()
-{
-	echo $'\e[31m'"$1" $'\e[0m'
-}
-
-function run()
-{
-	show "\$ $1"
-	eval "$1"
-	return $?
-}
-
-function abort()
-{
-	if [[ -n "$2" ]]; then
-		run "$2"
-	fi
-	echo $'\e[1;31merror:' "$1" $'\e[0m' >&2
-	exit 1
-}
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
 
 CMD="git status -uno"
 if [[ -n "$1" ]]; then
diff --git a/bin/setup_odbc b/bin/setup_odbc
--- a/bin/setup_odbc
+++ b/bin/setup_odbc
@@ -2,36 +2,7 @@
 
 # Sets up ODBC.
 
-###############################################################################
-# utilities
-###############################################################################
-function show
-{
-	echo $'\e[1;34m==>\e[0m\e[31m' "$1" $'\e[0m'
-}
-
-function run
-{
-	show "$1"
-	eval "$1"
-	return $?
-}
-
-function abort
-{
-	if [[ -n "$2" ]]; then
-		run "$2"
-	fi
-	echo $'\e[1;31merror:' "$1" $'\e[0m' >&2
-	exit 1
-}
-
-function ask
-{
-	echo -n $'\n\e[1;35m'
-	read -p "$1 (y/n) [n] ... "
-	echo -n $'\e[0;0m'
-}
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
 
 ###############################################################################
 # installing freetds with unixodbc
@@ -40,7 +11,7 @@ if ! type brew >/dev/null; then
 	abort "prerequisite homebrew not installed"
 fi
 
-function install_freetds
+install_freetds()
 {
 	run "brew install unixodbc" || abort "could not install unixodbc"
 	run "brew install --with-unixodbc freetds" || abort "could not install freetds with unixodbc"
@@ -130,7 +101,7 @@ run "cat $HOME/.odbc.ini"
 ###############################################################################
 # installing configuration files
 ###############################################################################
-function install_to
+install_to()
 {
 	local install_to_path="$@"
 	run "sudo mkdir -p $install_to_path/" || abort "can't create directory $install_to_path"
diff --git a/bin/update_bin b/bin/update_bin
--- a/bin/update_bin
+++ b/bin/update_bin
@@ -2,17 +2,16 @@
 
 # Syncs ./bin with ~/bin.
 
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
+
 EXCLUDES=(install usages macosver update_bin ignore)
 
 while read I; do EXCLUDES+=("$I"); done < ignore
 
-CMD="rsync -avl"
+CMD="rsync -apl"
 
 for I in "${EXCLUDES[@]}"; do
 	CMD="$CMD --exclude '$I'"
 done
 
-CMD="$CMD --delete ~/bin/ ."
-
-echo "$CMD"
-eval "$CMD"
+run "$CMD --delete ~/bin/ ." || abort "could not update bin"
diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,18 +1,8 @@
 #!/bin/bash
 
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
+
 set -e
-
-function show()
-{
-	echo $'\e[1;34m==>\e[0m\e[31m' $1 $'\e[0m'
-}
-
-function run()
-{
-	show "$1"
-	eval "$1"
-	return $?
-}
 
 if [ ! "$1" ]; then
 	echo "usage: $0 HOST"
@@ -21,7 +11,7 @@ if [ ! "$1" ]; then
 fi
 
 HOST="$1"
-REPO="$(basename $(pwd))"
+REPO="$(basename "$(pwd)")"
 
 run "tar zcvf - \"../$REPO\" | ssh $HOST \"tar xvzf -\""
 run "ssh $HOST \"cd '$REPO'; yes | ./install\""
diff --git a/env/dot_profile b/env/dot_profile
--- a/env/dot_profile
+++ b/env/dot_profile
@@ -198,7 +198,7 @@ if [[ -n "$(echo "$SHELL" | grep bash)" ]]; then
     _source_completions ~/.bash-completion/bash_completion 2>/dev/null # git.debian.org/git/bash-completion
     _source_completions ~/.complete 2>/dev/null # setup env
     if type brew >/dev/null 2>&1; then
-        source `brew --repository`/Library/Contributions/brew_bash_completion.sh
+        source "$(brew --repository)/Library/Contributions/brew_bash_completion.sh"
     fi
     complete -cf sudo
 elif [[ -n "$(echo "$SHELL" | grep zsh)" ]]; then
@@ -254,7 +254,7 @@ elif [[ -n "$(echo "$SHELL" | grep zsh)" ]]; then
     zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters
 
     # Directories
-    zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
+    zstyle ':completion:*:default' list-colors "${(s.:.)LS_COLORS}"
     zstyle ':completion:*:*:cd:*' tag-order local-directories directory-stack path-directories
     zstyle ':completion:*:*:cd:*:directory-stack' menu yes select
     zstyle ':completion:*:-tilde-:*' group-order 'named-directories' 'path-directories' 'users' 'expand'
@@ -267,7 +267,7 @@ elif [[ -n "$(echo "$SHELL" | grep zsh)" ]]; then
     zstyle ':completion:*:history-words' menu yes
 
     # Environmental Variables
-    zstyle ':completion::*:(-command-|export):*' fake-parameters ${${${_comps[(I)-value-*]#*,}%%,*}:#-*-}
+    zstyle ':completion::*:(-command-|export):*' fake-parameters "${${${_comps[(I)-value-*]#*,}%%,*}:#-*-}"
 
     # Populate hostname completion.
     zstyle -e ':completion:*:hosts' hosts 'reply=(
@@ -294,7 +294,7 @@ elif [[ -n "$(echo "$SHELL" | grep zsh)" ]]; then
     zstyle ':completion:*:rm:*' file-patterns '*:all-files'
 
     # Kill
-    zstyle ':completion:*:*:*:*:processes' command 'ps -u $USER -o pid,user,command -w'
+    zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,command -w"
     zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;36=0=01'
     zstyle ':completion:*:*:kill:*' menu yes select
     zstyle ':completion:*:*:kill:*' force-list always
@@ -343,7 +343,7 @@ _interactive_log "setup command prompt"
 ostype()
 {
     if [ -n "$OS" ]; then
-        echo $OS
+        echo "$OS"
         return 0
     fi
 
@@ -372,20 +372,20 @@ ostype()
 # allow user to provide override for terminal title
 title()
 {
-    export TERMINAL_TITLE_USER="$(echo "$@")"
+    export TERMINAL_TITLE_USER="$*"
 }
 
 # allow user to provide override for terminal prompt note
 note()
 {
-    export PROMPT_USER_NOTE="$(echo "$@")"
+    export PROMPT_USER_NOTE="$*"
 }
 
 # prints terminal note if one is set
 _prompt_usernote()
 {
     if [[ -n "$PROMPT_USER_NOTE" ]]; then
-        echo -n " #" $PROMPT_USER_NOTE
+        echo -n " #" "$PROMPT_USER_NOTE"
     fi
 }
 
@@ -397,7 +397,7 @@ _prompt_python_env()
         PROMPT_PYTHON_ENV=" # [$PYTHON_ENV"
 
         if [[ -n "$VIRTUAL_ENV" ]]; then
-            PROMPT_PYTHON_ENV="$PROMPT_PYTHON_ENV:`basename \"$VIRTUAL_ENV\"`"
+            PROMPT_PYTHON_ENV="$PROMPT_PYTHON_ENV:$(basename "$VIRTUAL_ENV")"
         elif [[ -n "$CONDA_DEFAULT_ENV" ]]; then
             PROMPT_PYTHON_ENV="$PROMPT_PYTHON_ENV:$CONDA_DEFAULT_ENV"
         fi
@@ -444,14 +444,13 @@ if [[ -n "$(echo "$SHELL" | grep bash)" ]]; then
         local BGREEN="\[\e[1;32m\]"
         local  BLACK="\[\e[0m\]"
         local   GREY="\[\e[0;38;5;241m\]"
-        local COLOR_NONE="\[\e[0m\]"
 
         # "\w" or "${PWD/#$HOME/~}" not sure which to go with...
-        local TERMINAL_TITLE="$TERMINAL_TITLE_USER`if [[ -n \"$TERMINAL_TITLE_USER\" ]]; then printf ' '; fi`$USER@$HOST:\w"
+        local TERMINAL_TITLE="$TERMINAL_TITLE_USER$(if [[ -n \"$TERMINAL_TITLE_USER\" ]]; then printf ' '; fi)$USER@$HOST:\w"
         local PROMPT_LINE_1="$RED\w${BLUE}$(_prompt_python_env)$GREY$(_prompt_repo)$BLUE$(_prompt_usernote)"
         local PROMPT_LINE_2="$RED$(date +%H%M) $(ostype | sed 's/Linux-//g') \u@\h\`if [ \$? = 0 ]; then echo \"$BGREEN\$\"; else echo \"$BRED>\"; fi\`$BLACK"
 
-        PS1="\e]2;${TERMINAL_TITLE}\a\
+        PS1="\[\e]2;\]${TERMINAL_TITLE}\a\
 ${PROMPT_LINE_1}\n\
 ${PROMPT_LINE_2} "
         PS2="> "
@@ -492,7 +491,7 @@ elif [[ -n "$(echo "$SHELL" | grep zsh)" ]]; then
 
     _prompt_cursor()
     {
-        echo -n "%(?|%2F|%1F)%(?|$|>)%{$reset_color%} "
+        echo -n "%(?|%2F|%1F)%(?|\$|>)%{$reset_color%} "
     }
 
     _prompt_second_line()
@@ -558,16 +557,6 @@ h()
     fi
 }
 
-fuck()
-{
-    die $1
-    if [[ $? == 0 ]]; then
-        echo
-        echo " (╯°□°）╯︵$(echo $1|flip 2>/dev/null)"
-        echo
-    fi
-}
-
 # use gnu-sed if available
 if type gsed >/dev/null 2>&1; then
     alias sed='gsed '
@@ -578,7 +567,7 @@ fi
 ################################################################################
 _interactive_log "setup terminal colors and editors"
 if type dircolors >/dev/null 2>&1; then
-    eval `dircolors -b ~/.dircolors 2>/dev/null`
+    eval "$(dircolors -b "$HOME/.dircolors" 2>/dev/null)"
     alias ls='ls -hF --color=auto'
 fi
 export CLICOLOR=1
@@ -620,10 +609,13 @@ export LESS_TERMCAP_us=$'\E[01;32m'
 ################################################################################
 # source any local configuration files
 ################################################################################
-for I in `/bin/ls -1 ~/.profile_* 2>/dev/null` ; do
+IFS=$'\n'
+for I in $(/bin/ls -1 ~/.profile_* 2>/dev/null) ; do
     _interactive_log "sourcing $I"
-    . "$I"
+    source "$I"
 done
+
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
 
 _interactive_log "environment setup complete"
 
diff --git a/env/install b/env/install
--- a/env/install
+++ b/env/install
@@ -1,13 +1,13 @@
 #!/bin/bash
 
-function sync()
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
+
+sync()
 {
-	CMD="rsync -avl \"$1\" \"$2/$1\""
-	echo "+ $CMD"
-	eval $CMD
+	run "rsync -apl '$1' '$2/$1'"
 }
 
-function contains()
+contains()
 {
 	local e
 	for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
@@ -19,92 +19,90 @@ function contains()
 ###############################################################################
 
 declare -a DOT_FILES
-DOT_FILES=($(find * -maxdepth 1 -name "dot_*"))
+DOT_FILES=($(find ./* -maxdepth 1 -name "dot_*"))
 if [[ -n "$1" ]]; then
 	DOT_FILES=("$@")
 fi
-echo "installing dot files: ${DOT_FILES[@]}..."
+show "installing dot files: ${DOT_FILES[@]}..."
 
 for I in dot_*; do
-	if contains "$I" "${DOT_FILES[@]}"; then
+	if contains "./$I" "${DOT_FILES[@]}"; then
 		if [[ -f $I ]]; then
-			if [[ -n "$(echo $I | grep profile_)" ]]; then
-				read -p "install $I? (y/n) [n] ... "
+			if [[ -n "$(echo "$I" | grep profile_)" ]]; then
+				ask "install $I?"
 			else
 				REPLY="y"
 			fi
 			if [[ "$REPLY" == "y" ]]; then
-				CMD="rsync -avl $I ~/.$(echo $(basename $I) | sed s/^dot_//)"
-				echo "+ $CMD"
-				eval $CMD
+				run "rsync -apl '$I' '$HOME/.$(basename "$I" | sed s/^dot_//)'"
 			fi
 		elif [[ -d $I ]]; then
-			CMD="rsync -avl $I/* ~/.$(echo $(basename $I) | sed s/^dot_//)/"
-			echo "+ $CMD"
-			eval $CMD
+			run "rsync -apl '$I/'* '$HOME/.$(basename "$I" | sed s/^dot_//)/'"
 		else
-			echo "error: could not install '$I'" >&2
+			abort "could not install '$I'"
 		fi
 	fi
 done
 
 if [[ -n "$1" ]]; then
-	echo "dot file install complete!"
+	show "dot file install complete!"
 	exit 0
 fi
 
 ###############################################################################
 # Install bash-completion form debian:
 ###############################################################################
-if type git 2>/dev/null; then
+if type git 1>/dev/null 2>&1; then
 	# From git:
 	if [[ -d ~/.bash-completion ]]; then
-		cd ~/.bash-completion
-		git fetch 
-		git clean -f 
-		git reset --hard origin/master
-		cd -
+		(
+			run "pushd '$HOME/.bash-completion'"
+		  	run "git fetch"
+		  	run "git clean -f"
+		  	run "git reset --hard origin/master"
+		)
 	else
-		cd ~
-		git clone git://git.debian.org/git/bash-completion/bash-completion .bash-completion
-		cd -
+		(
+			run "pushd '$HOME'"
+		  	run "git clone git://git.debian.org/git/bash-completion/bash-completion .bash-completion"
+		)
 	fi
 else
 	# From tarball:
 	CURL_OUTPUT=$(mktemp -d -t tmp.XXXXXXXXXX)
-	trap "rm -rf $CURL_OUTPUT" EXIT
+	trap 'rm -rf $CURL_OUTPUT' EXIT
 	LATEST_BASH_COMPLETION="$(curl -s --show-error http://bash-completion.alioth.debian.org/files/ | sed 's/.*href="\([^"]*\)">[^<]*<\/a><\/td><td align="right">\([^<]*\).*/\1 \2/g' | egrep "^bash-completion.*tar.gz " | sort -k2 -d | tail -n 1 | cut -f1 -d' ')"
-	pushd "$CURL_OUTPUT"
-	curl -s --show-error -O "http://bash-completion.alioth.debian.org/files/$LATEST_BASH_COMPLETION"
-	mkdir -p "$HOME/.bash-completion"; tar xvzf "$LATEST_BASH_COMPLETION" -C "$HOME/.bash-completion" --strip-components=1
-	popd
+	(
+		run "pushd '$CURL_OUTPUT'"
+	  	run "curl -s --show-error -O 'http://bash-completion.alioth.debian.org/files/$LATEST_BASH_COMPLETION'"
+      	run "mkdir -p '$HOME/.bash-completion'"
+	  	run "tar xvzf '$LATEST_BASH_COMPLETION' -C '$HOME/.bash-completion' --strip-components=1"
+	)
 fi
 
 ###############################################################################
 # Install Sublime Text packages
 ###############################################################################
-function grab_package()
+grab_package()
 {
 	URL="$1"
 	NAME="$2"
 
-	pushd ~/"Library/Application Support/Sublime Text 3/Packages"
-	if [[ -d "$NAME" ]]; then
-		pushd "$NAME"
-		git pull -u
-		popd
-	else
-		git clone "$URL" "$NAME"
-	fi
-	popd
+	(
+		run "pushd '$HOME/Library/Application Support/Sublime Text 3/Packages'"
+		if [[ -d "$NAME" ]]; then
+			( run "pushd '$NAME'"; run "git pull -u" )
+		else
+			run "git clone '$URL' '$NAME'"
+		fi
+	)
 }
 
 if [[ -d "$HOME/Library/Application Support/Sublime Text 3/Packages/User" ]]; then
-	grab_package https://github.com/buymeasoda/soda-theme.git "Theme - Soda"
-	grab_package https://github.com/JulianEberius/SublimePythonIDE.git "SublimePythonIDE"
-
-	sync "Preferences.sublime-settings" ~/"Library/Application Support/Sublime Text 3/Packages/User"
-	sync "SublimePython.sublime-settings" ~/"Library/Application Support/Sublime Text 3/Packages/User"
+	grab_package "https://github.com/buymeasoda/soda-theme.git" "Theme - Soda"
+	grab_package "https://github.com/JulianEberius/SublimePythonIDE.git" "SublimePythonIDE"
+	sync "Preferences.sublime-settings" "$HOME/Library/Application Support/Sublime Text 3/Packages/User"
+	sync "SublimePython.sublime-settings" "$HOME/Library/Application Support/Sublime Text 3/Packages/User"
 fi
 
-echo "env install complete!"
+show "env install complete!"
diff --git a/env/update_env b/env/update_env
--- a/env/update_env
+++ b/env/update_env
@@ -2,38 +2,38 @@
 
 # updates env with whatever new changes are found in the current environment
 
-function backup()
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
+
+backup()
 {
-	rsync -avl "$1/$2" "$2"
+	run "rsync -apl '$1/$2' '$2'"
 }
 
 # profile
-rsync -avl ~/.profile ./dot_profile
-for I in ~/.profile_*; do
-    echo "considering: $I"
+run "rsync -apl '$HOME/.profile' ./dot_profile"
+for I in "$HOME/".profile_*; do
     if [[ -z "$(grep "$(basename "$I")" ignore)" ]]; then
-        echo "adding: $I"
-        rsync -avl "$I" "./$(basename "$I" | sed 's/^./dot_/')"
+        run "rsync -apl '$I' './$(basename "$I" | sed 's/^./dot_/')'"
     fi
 done
 
 # bash
-rsync -avl ~/.bash_profile ./dot_bash_profile
-rsync -avl ~/.bashrc ./dot_bashrc
+run "rsync -apl '$HOME/.bash_profile' ./dot_bash_profile"
+run "rsync -apl '$HOME/.bashrc' ./dot_bashrc"
 
 # zsh
-rsync -avl ~/.zshrc ./dot_zshrc
+run "rsync -apl '$HOME/.zshrc' ./dot_zshrc"
 
 # tools
-rsync -avl ~/.dircolors ./dot_dircolors
-rsync -avl ~/.inputrc ./dot_inputrc
-rsync -avl ~/.vimrc ./dot_vimrc
-rsync -avl ~/.hgignore ./dot_hgignore
-rsync -avl ~/.hgrc ./dot_hgrc
-rsync -avl ~/.gitconfig ./dot_gitconfig
-rsync -avl ~/.pythonrc.py ./dot_pythonrc.py
-rsync -avl ~/.toprc ./dot_toprc
-rsync -avl ~/.complete/ ./dot_complete
+run "rsync -apl '$HOME/.dircolors' ./dot_dircolors"
+run "rsync -apl '$HOME/.inputrc' ./dot_inputrc"
+run "rsync -apl '$HOME/.vimrc' ./dot_vimrc"
+run "rsync -apl '$HOME/.hgignore' ./dot_hgignore"
+run "rsync -apl '$HOME/.hgrc' ./dot_hgrc"
+run "rsync -apl '$HOME/.gitconfig' ./dot_gitconfig"
+run "rsync -apl '$HOME/.pythonrc'.py ./dot_pythonrc.py"
+run "rsync -apl '$HOME/.toprc' ./dot_toprc"
+run "rsync -apl '$HOME/.complete/' ./dot_complete"
 
-backup ~/"Library/Application Support/Sublime Text 3/Packages/User" "Preferences.sublime-settings"
-backup ~/"Library/Application Support/Sublime Text 3/Packages/User" "SublimePython.sublime-settings"
+backup "$HOME/Library/Application Support/Sublime Text 3/Packages/User" "Preferences.sublime-settings"
+backup "$HOME/Library/Application Support/Sublime Text 3/Packages/User" "SublimePython.sublime-settings"
diff --git a/update b/update
--- a/update
+++ b/update
@@ -2,19 +2,22 @@
 
 # Updates the bin and env directories with whatever new changes are found in the current environment
 
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
+
 set -e
 
 if [[ -n "$(git status -s)" ]]; then
-	echo "cowardly refusing to overwrite existing changes" >&2
-	exit 1
+	abort "cowardly refusing to overwrite existing changes"
 fi
 
-pushd bin
-./update_bin
-perl -ni -e 'print unless /^\|.*/' ../README.md 
-./usages -t >>../README.md 
-popd
+(
+	run "pushd bin"
+	run "./update_bin"
+	run "perl -ni -e 'print unless /^\|.*/' ../README.md"
+	run "./usages -t >>../README.md"
+)
 
-pushd env
-./update_env
-popd
+(
+	run "pushd env"
+	run "./update_env"
+)
