Removing install_atom script, now handled by install_dev.

diff --git a/bin/install_dev b/bin/install_dev
--- a/bin/install_dev
+++ b/bin/install_dev
@@ -16,7 +16,11 @@ HOMEBREW_FORMULAS="autoconf boost cmake coreutils cppunit dmd doxygen fontconfig
 
 HOMEBREW_CASKS="google-chrome pdftk caffeine skype firefox gimp-lisanet iterm2   \
     kaleidoscope mysqlworkbench dbvisualizer evernote pycharm-ce steam mactex    \
-    sourcetree texshop istumbler"
+    sourcetree texshop istumbler adium atom flux"
+
+ATOM_PACKAGES=" atom-soda-dark-ui autocomplete-plus linter linter-flake8         \
+    linter-shellcheck merge-conflicts minimap minimap-git-diff minimap-selection \
+    monokai-soda red-wavy-underline set-syntax sort-lines tabs-to-spaces"
 
 PIP_PACKAGES="bson pymongo fabric iniparse psycopg2 oauth2client pytz suds       \
     google-api-python-client httplib2 tinycss termcolor requests uritemplate     \
@@ -52,6 +56,8 @@ usage()
     echo "" >&2
     echo "Homebrew Casks: $(echo "$HOMEBREW_CASKS" | sed "s/  */, /g" | fold -w 80 -s)" >&2
     echo "" >&2
+    echo "Atom Packages: $(echo "$ATOM_PACKAGES" | sed "s/  */, /g" | fold -w 80 -s)" >&2
+    echo "" >&2
     echo "Pip Packages: $(echo "$PIP_PACKAGES" | sed "s/  */, /g" | fold -w 80 -s)" >&2
     echo "" >&2
     echo "Conda Packages: $(echo "$CONDA_PACKAGES" | sed "s/  */, /g" | fold -w 80 -s)" >&2
@@ -61,6 +67,10 @@ usage()
 }
 
 source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
+
+# create download cache
+DL_CACHE="$HOME/.install_dev"
+mkdir -p "$DL_CACHE"
 
 ################################################################################
 # Steps
@@ -114,7 +124,7 @@ install_brew_formula()
 install_brew_cask()
 {
     if ! brew ls | grep -q "$1"; then
-        run "brew cask install  '$1'"
+        run "brew cask install '$1'"
     else
         show "brew formula '$1' already installed"
     fi
@@ -257,11 +267,11 @@ step_install_xquartz() # xquartz
     local tempdir="$(mktemp -d -t tmp.XXXXXXXXXX)" || abort "can't create temp directory"
     local cleanup="umount /Volumes/$(basename "$latest" .dmg); rm -rf $tempdir"
     run "cd $tempdir" || abort "can't enter temp directory" "$cleanup"
-    if [[ ! -f "/tmp/.install_dev/$latest" ]] ; then
+    if [[ ! -f "$DL_CACHE/$latest" ]] ; then
         run "wget -c http://xquartz.macosforge.org/downloads/SL/$latest" || abort "can't acquire $latest" "$cleanup"
-        run "cp $latest /tmp/.install_dev/$latest"
+        run "cp $latest '$DL_CACHE/$latest'"
     else
-        run "cp /tmp/.install_dev/$latest ."
+        run "cp '$DL_CACHE/$latest' ."
     fi
     run "hdiutil mount $latest" || abort "can't mount $latest at /Volumes/$(basename "$latest" .dmg)" "$cleanup"
     run "sudo installer -pkg /Volumes/$(basename "$latest" .dmg)/XQuartz.pkg -target /" || abort "installer failed" "$cleanup"
@@ -302,6 +312,26 @@ step_install_zsh() # zsh
     HB_ZSH_BINARY="/usr/local/bin/zsh"
     ensure_install_shell "$HB_ZSH_BINARY"
     run "chsh -s '$HB_ZSH_BINARY' '$(whoami)'"
+}
+
+install_atom_pkg()
+{
+    local PKG="$1"
+    local INSTALLED="$(apm list --installed --bare | grep "$PKG")"
+    if [[ -z "$INSTALLED" ]]; then
+        run "apm install $PKG" || abort "can not install package '$PKG'"
+    else
+        show "skipping $PKG: already installed"
+    fi
+}
+
+step_install_atom() # atom
+{
+    install_brew_cask atom || abort "can't install atom via brew-cask"
+    IFS=$" "
+    for I in $ATOM_PACKAGES; do
+        install_atom_pkg "$I"
+    done
 }
 
 step_install_tiddlywiki() # tiddlywiki
@@ -394,8 +424,6 @@ if [[ $LISTING == 0 ]]; then
     echo "$(tput bold)Prerequisite: Install 'Command Line Tools' from $(tput smul)http://developer.apple.com/downloads$(tput rmul) or from X Code preferences$(tput sgr0)"
 fi
 
-mkdir -p /tmp/.install_dev # download cache
-
 # key; question; function
 steps=("xcode;Check that Command Line Tools are installed;step_setup_xcode
 brew;Upgrade/Install Homebrew formulas;step_install_homebrew
@@ -404,6 +432,7 @@ python;Upgrade/Install Anaconda, pip packages, and conda packages;step_install_p
 java;Check that java is installed (will prompt to install if not);step_check_java
 gem;Upgrade/Install gem packages + rubygems-update package;step_install_gem
 xquartz;Install latest XQuartz package;step_install_xquartz
+atom;Upgrade/Install latest Atom and packages from Homebrew Cask;step_install_atom
 bash;Install latest version of bash from Homebrew;step_install_bash
 zsh;Install latest version of zsh from Homebrew;step_install_zsh
 tiddlywiki;Install and setup latest TiddlyWiki from Homebrew;step_install_tiddlywiki")
