Cleaning up install_dev a bit.

diff --git a/bin/install_dev b/bin/install_dev
--- a/bin/install_dev
+++ b/bin/install_dev
@@ -5,9 +5,9 @@
 ################################################################################
 # Settings
 ################################################################################
-HOMEBREW_FORMULAS="git git-flow mpfr ruby openssl autoconf libtiff libtool cmake wget mercurial unixodbc postgresql spark ncftp cppunit tclap pcre plotutils jpeg libpng freetype fontconfig ghostscript imagemagick doxygen coreutils gnu-sed gfortran ipopt mongodb scons boost dmd yaml-cpp pidof ansible mysql unrar sqlite"
-PIP_PACKAGES="bson pymongo fabric iniparse psycopg2 suds pyzmq oauth2client google-api-python-client httplib2"
-GEM_PACKAGES="cap_gun archive-tar-minitar bson bson_ext bundler bundler-unload childprocess cuba erector gem-wrappers jekyll jewelbox log4r lolcat mongo net-ldap rack rack-protection railsless-deploy rubygems-bundler rvm shotgun tiny_tds vagrant yajl-ruby"
+HOMEBREW_FORMULAS="git git-flow mpfr ruby openssl autoconf libtiff libtool cmake wget mercurial unixodbc postgresql spark ncftp cppunit tclap pcre plotutils jpeg libpng freetype fontconfig ghostscript imagemagick doxygen coreutils gnu-sed gfortran mongodb scons boost dmd yaml-cpp pidof ansible mysql unrar sqlite"
+PIP_PACKAGES="bson pymongo fabric iniparse psycopg2 suds pyzmq oauth2client google-api-python-client httplib2 tinycss"
+GEM_PACKAGES="cap_gun archive-tar-minitar bson bson_ext bundler bundler-unload childprocess cuba erector gem-wrappers jekyll jewelbox log4r lolcat mongo net-ldap rack rack-protection railsless-deploy rubygems-bundler rvm shotgun tiny_tds vagrant yajl-ruby capistrano"
 
 ################################################################################
 # Utilities
@@ -61,6 +61,18 @@ function ask()
 	echo -n $'\e[0;0m'
 }
 
+################################################################################
+# Steps
+################################################################################
+function step_setup_xcode()
+{
+	export SELECT="select"
+	if [[ -z "$(which xcode-$SELECT)" ]]; then
+		abort "install Xcode Command Line Tools first"
+	fi
+	show "Xcode Command Line Tools properly installed."
+}
+
 function install_brew_formula()
 {
 	if [[ -z "$(brew ls | grep $1)" ]]; then
@@ -71,22 +83,6 @@ function install_brew_formula()
 
 	# force link the most recent versions
 	run "brew unlink $1 && brew link --force --overwrite $1"
-}
-
-################################################################################
-# Steps
-################################################################################
-function step_setup_xcode()
-{
-	export SELECT="select"
-	if [[ -z "$(which xcode-$SELECT)" ]]; then
-		abort "install Xcode Command Line Tools first"
-	fi
-	if [[ "$(xcode-$SELECT -print-path)" != "/Applications/Xcode.app/Contents/Developer" ]]; then
-		run "sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer" || abort "failed to select xcode properly"
-	else
-		show "Xcode already selected to /Applications/Xcode.app/Contents/Developer"
-	fi
 }
 
 function step_install_homebrew()
@@ -130,28 +126,6 @@ function step_install_homebrew()
 	run "brew unlink openssl"
 }
 
-function step_install_bash()
-{
-	if [[ -z "$(which brew)" ]]; then
-		abort "please install Homebrew first"
-	fi
-
-	run "brew update"
-	if [[ -z "$(brew ls | grep bash)" ]]; then
-		run "brew install bash"
-	else
-		run "brew upgrade bash"
-	fi
-
-	local BASH_BINARY="$(brew ls bash | grep '^.*/bin/.*bash$')"
-	local INSTALLED="$(grep "$BASH_BINARY" /etc/shells)"
-	if [[ "$INSTALLED" == "" ]]; then
-		run "echo \"$BASH_BINARY\" | sudo tee -a /etc/shells"
-	fi
-
-	show "Please set your terminal shell to \"$BASH_BINARY\""
-}
-
 function cleanup_install_anaconda()
 {
 	[[ -n "$curl_output" ]] && rm -f "$curl_output"
@@ -175,7 +149,7 @@ function step_install_python
 	# Install python packages that don't come with Anaconda... yet!
 	IFS=$" "
 	for I in $PIP_PACKAGES; do
-		run "sudo pip install -U $I"
+		run "pip install -U $I"
 	done
 
 	# Fix annoying ipython settings
@@ -225,6 +199,52 @@ function step_install_pyodbc()
 	run "$cleanup"
 }
 
+function step_install_bison_3()
+{
+	if [[ -n "$(bison -V | head -n 1 | grep 3.0)" ]]; then
+		show "a bison 3.0 is already installed..."
+		ask "Force re-install?"
+		[[ "$REPLY" == "y" ]] || return
+	fi
+
+	local tempdir="$(mktemp -d -t tmp.XXXXXXXXXX)" || abort "can't create temp directory"
+	local cleanup="rm -rf $tempdir"
+	run "cd $tempdir" || abort "can't enter temp directory" "$cleanup"
+	if [[ ! -f /tmp/.install_dev/bison-3.0.tar.gz ]] ; then
+		run "wget -c http://ftp.gnu.org/gnu/bison/bison-3.0.tar.gz" || abort "can't acquire source" "$cleanup"
+		run "cp bison-3.0.tar.gz /tmp/.install_dev/bison-3.0.tar.gz"
+	else
+		run "cp /tmp/.install_dev/bison-3.0.tar.gz ."
+	fi
+	run "tar zfx bison-3.0.tar.gz" || abort "build step failed" "$cleanup"
+	run "cd bison-3.0" || abort "build step failed" "$cleanup"
+		run "./configure --prefix=/usr CFLAGS=-O3 && make" || abort "build step failed" "$cleanup"
+		run "sudo make install" || abort "build step failed" "$cleanup"
+	run "$cleanup"
+}
+
+function step_install_xquartz_275()
+{
+	if type Xquartz >/dev/null 2>&1; then
+		show "a Xquartz is already installed..."
+		ask "Force re-install?"
+		[[ "$REPLY" == "y" ]] || return
+	fi
+
+	local tempdir="$(mktemp -d -t tmp.XXXXXXXXXX)" || abort "can't create temp directory"
+	local cleanup="umount /Volumes/XQuartz-2.7.5; rm -rf $tempdir"
+	run "cd $tempdir" || abort "can't enter temp directory" "$cleanup"
+	if [[ ! -f /tmp/.install_dev/XQuartz-2.7.5.dmg ]] ; then
+		run "wget -c http://xquartz.macosforge.org/downloads/SL/XQuartz-2.7.5.dmg" || abort "can't acquire XQuartz-2.7.5.dmg" "$cleanup"
+		run "cp XQuartz-2.7.5.dmg /tmp/.install_dev/XQuartz-2.7.5.dmg"
+	else
+		run "cp /tmp/.install_dev/XQuartz-2.7.5.dmg ."
+	fi
+	run "hdiutil mount XQuartz-2.7.5.dmg" || abort "can't mount XQuartz-2.7.5.dmg on /Volumes/XQuartz-2.7.5" "$cleanup"
+	run "sudo installer -pkg /Volumes/XQuartz-2.7.5/XQuartz.pkg -target /" || abort "installer failed" "$cleanup"
+	run "$cleanup"
+}
+
 function step_install_mongo_c_driver_071()
 {
 	if [[ -f "/usr/local/lib/libmongoc.a" ]]; then
@@ -243,6 +263,28 @@ function step_install_mongo_c_driver_071()
 	run "scons" || abort "build step failed" "$cleanup"
 	run "sudo make install" || abort "build step failed" "$cleanup"
 	run "$cleanup"
+}
+
+function step_install_bash()
+{
+	if [[ -z "$(which brew)" ]]; then
+		abort "please install Homebrew first"
+	fi
+
+	run "brew update"
+	if [[ -z "$(brew ls | grep bash)" ]]; then
+		run "brew install bash"
+	else
+		run "brew upgrade bash"
+	fi
+
+	local BASH_BINARY="$(brew ls bash | grep '^.*/bin/.*bash$')"
+	local INSTALLED="$(grep "$BASH_BINARY" /etc/shells)"
+	if [[ "$INSTALLED" == "" ]]; then
+		run "echo \"$BASH_BINARY\" | sudo tee -a /etc/shells"
+	fi
+
+	show "Please set your terminal shell to \"$BASH_BINARY\""
 }
 
 function step_install_ccache_319()
@@ -268,78 +310,9 @@ function step_install_ccache_319()
 	run "sudo make install" || abort "build step failed" "$cleanup"
 	run "sudo ln -fs /usr/local/bin/ccache /usr/local/bin/gcc" || abort "unable to symlink ccache" "$cleanup"
 	run "sudo ln -fs /usr/local/bin/ccache /usr/local/bin/g++" || abort "unable to symlink ccache" "$cleanup"
+	run "sudo ln -fs /usr/local/bin/ccache /usr/local/bin/c++" || abort "unable to symlink ccache" "$cleanup"
 	run "sudo ln -fs /usr/local/bin/ccache /usr/local/bin/clang" || abort "unable to symlink ccache" "$cleanup"
 	run "sudo ln -fs /usr/local/bin/ccache /usr/local/bin/clang++" || abort "unable to symlink ccache" "$cleanup"
-	run "$cleanup"
-}
-
-function step_install_bison_3()
-{
-	if [[ -n "$(bison -V | head -n 1 | grep 3.0)" ]]; then
-		show "a bison 3.0 is already installed..."
-		ask "Force re-install?"
-		[[ "$REPLY" == "y" ]] || return
-	fi
-
-	local tempdir="$(mktemp -d -t tmp.XXXXXXXXXX)" || abort "can't create temp directory"
-	local cleanup="rm -rf $tempdir"
-	run "cd $tempdir" || abort "can't enter temp directory" "$cleanup"
-	if [[ ! -f /tmp/.install_dev/bison-3.0.tar.gz ]] ; then
-		run "wget -c http://ftp.gnu.org/gnu/bison/bison-3.0.tar.gz" || abort "can't acquire source" "$cleanup"
-		run "cp bison-3.0.tar.gz /tmp/.install_dev/bison-3.0.tar.gz"
-	else
-		run "cp /tmp/.install_dev/bison-3.0.tar.gz ."
-	fi
-	run "tar zfx bison-3.0.tar.gz" || abort "build step failed" "$cleanup"
-	run "cd bison-3.0" || abort "build step failed" "$cleanup"
-		run "./configure --prefix=/usr CFLAGS=-O3 && make" || abort "build step failed" "$cleanup"
-		run "sudo make install" || abort "build step failed" "$cleanup"
-	run "$cleanup"
-}
-
-function step_install_flex_2537()
-{
-	if [[ -n "$(flex -V | head -n 1 | grep 2.5.37)" ]]; then
-		show "a flex 2.5.37 is already installed..."
-		ask "Force re-install?"
-		[[ "$REPLY" == "y" ]] || return
-	fi
-
-	local tempdir="$(mktemp -d -t tmp.XXXXXXXXXX)" || abort "can't create temp directory"
-	local cleanup="rm -rf $tempdir"
-	run "cd $tempdir" || abort "can't enter temp directory" "$cleanup"
-	if [[ ! -f /tmp/.install_dev/flex-2.5.37.tar.gz ]] ; then
-		run "wget -c http://hivelocity.dl.sourceforge.net/project/flex/flex-2.5.37.tar.gz" || abort "can't acquire source" "$cleanup"
-		run "cp flex-2.5.37.tar.gz /tmp/.install_dev/flex-2.5.37.tar.gz"
-	else
-		run "cp /tmp/.install_dev/flex-2.5.37.tar.gz ."
-	fi
-	run "tar zfx flex-2.5.37.tar.gz" || abort "build step failed" "$cleanup"
-	run "cd flex-2.5.37" || abort "build step failed" "$cleanup"
-		run "./configure --prefix=/usr CFLAGS=-O3 && make" || abort "build step failed" "$cleanup"
-		run "sudo make install" || abort "build step failed" "$cleanup"
-	run "$cleanup"
-}
-
-function step_install_xquartz_275()
-{
-	if type Xquartz >/dev/null 2>&1; then
-		show "a Xquartz is already installed..."
-		ask "Force re-install?"
-		[[ "$REPLY" == "y" ]] || return
-	fi
-
-	local tempdir="$(mktemp -d -t tmp.XXXXXXXXXX)" || abort "can't create temp directory"
-	local cleanup="umount /Volumes/XQuartz-2.7.5; rm -rf $tempdir"
-	run "cd $tempdir" || abort "can't enter temp directory" "$cleanup"
-	if [[ ! -f /tmp/.install_dev/XQuartz-2.7.5.dmg ]] ; then
-		run "wget -c http://xquartz.macosforge.org/downloads/SL/XQuartz-2.7.5.dmg" || abort "can't acquire XQuartz-2.7.5.dmg" "$cleanup"
-		run "cp XQuartz-2.7.5.dmg /tmp/.install_dev/XQuartz-2.7.5.dmg"
-	else
-		run "cp /tmp/.install_dev/XQuartz-2.7.5.dmg ."
-	fi
-	run "hdiutil mount XQuartz-2.7.5.dmg" || abort "can't mount XQuartz-2.7.5.dmg on /Volumes/XQuartz-2.7.5" "$cleanup"
-	run "sudo installer -pkg /Volumes/XQuartz-2.7.5/XQuartz.pkg -target /" || abort "installer failed" "$cleanup"
 	run "$cleanup"
 }
 
@@ -380,9 +353,8 @@ fi
 steps=("xcode;sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer?;step_setup_xcode
 brew;Upgrade/Install Homebrew, formulas: $HOMEBREW_FORMULAS?;step_install_homebrew
 python;Upgrade/Install Anaconda, pip packages: $PIP_PACKAGES?;step_install_python
-gem;Upgrade/Install gem packages: rubygems-update capistrano-v2.15.5 $GEM_PACKAGES?;step_install_gem
+gem;Upgrade/Install gem packages: rubygems-update $GEM_PACKAGES?;step_install_gem
 pyodbc;Install pyodbc (patched for unixODBC on OS X)?;step_install_pyodbc
-flex;Install flex 2.5.37 from source?;step_install_flex_2537
 bison;Install bison 3.0 from source?;step_install_bison_3
 XQuartz;Install XQuartz 2.7.5 package?;step_install_xquartz_275
 mongo;Install mongo-c-driver v0.7.1 from source?;step_install_mongo_c_driver_071
