bin/install_dev: use wget in continune mode

diff --git a/bin/install_dev b/bin/install_dev
--- a/bin/install_dev
+++ b/bin/install_dev
@@ -171,8 +171,8 @@ function step_install_pip
 
 	# Fix annoying ipython settings
 	run "ipython profile create"
-	run "perl -pie 's/.*confirm_exit.*/c.TerminalInteractiveShell.confirm_exit = False/' $HOME/.ipython/profile_default/ipython_config.py"
-	run "perl -pie 's/.*display_banner.*/c.TerminalIPythonApp.display_banner = False/' $HOME/.ipython/profile_default/ipython_config.py"
+	run "perl -pi -e 's/.*confirm_exit.*/c.TerminalInteractiveShell.confirm_exit = False/' $HOME/.ipython/profile_default/ipython_config.py"
+	run "perl -pi -e 's/.*display_banner.*/c.TerminalIPythonApp.display_banner = False/' $HOME/.ipython/profile_default/ipython_config.py"
 }
 
 function step_install_gem()
@@ -189,11 +189,17 @@ function step_install_gem()
 
 function step_install_ccache_319()
 {
+	if [[ -n "$(ccache -V | head -n 1 | grep 3.1.9)" ]]; then
+		show "a ccache is already installed..."
+		ask "Force re-install?"
+		[[ "$REPLY" == "y" ]] || return
+	fi
+
 	local tempdir="$(mktemp -d -t tmp.XXXXXXXXXX)" || abort "can't create temp directory"
 	local cleanup="rm -rf $tempdir"
 	run "cd $tempdir" || abort "can't enter temp directory" "$cleanup"
 	if [[ ! -f /tmp/.install_dev/ccache-3.1.9.tar.gz ]] ; then
-		run "wget http://samba.org/ftp/ccache/ccache-3.1.9.tar.gz" || abort "can't acquire source" "$cleanup"
+		run "wget -c http://samba.org/ftp/ccache/ccache-3.1.9.tar.gz" || abort "can't acquire source" "$cleanup"
 		run "cp ccache-3.1.9.tar.gz /tmp/.install_dev/ccache-3.1.9.tar.gz"
 	else
 		run "cp /tmp/.install_dev/ccache-3.1.9.tar.gz ."
@@ -211,11 +217,17 @@ function step_install_ccache_319()
 
 function step_install_xquartz_274()
 {
+	if type Xquartz >/dev/null 2>&1; then
+		show "a Xquartz is already installed..."
+		ask "Force re-install?"
+		[[ "$REPLY" == "y" ]] || return
+	fi
+
 	local tempdir="$(mktemp -d -t tmp.XXXXXXXXXX)" || abort "can't create temp directory"
 	local cleanup="umount /Volumes/XQuartz-2.7.4; rm -rf $tempdir"
 	run "cd $tempdir" || abort "can't enter temp directory" "$cleanup"
 	if [[ ! -f /tmp/.install_dev/XQuartz-2.7.4.dmg ]] ; then
-		run "wget http://xquartz.macosforge.org/downloads/SL/XQuartz-2.7.4.dmg" || abort "can't acquire XQuartz-2.7.4.dmg" "$cleanup"
+		run "wget -c http://xquartz.macosforge.org/downloads/SL/XQuartz-2.7.4.dmg" || abort "can't acquire XQuartz-2.7.4.dmg" "$cleanup"
 		run "cp XQuartz-2.7.4.dmg /tmp/.install_dev/XQuartz-2.7.4.dmg"
 	else
 		run "cp /tmp/.install_dev/XQuartz-2.7.4.dmg ."
