Ran shfmt on bin/setup, update some vscode config.

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -122,9 +122,9 @@ cleanup_item_list() {
                     for ((i = 1; i <= leftover; i++)); do
                         echo -n ' '
                     done
-                    echo "\\"
+                    echo '\'
                 else
-                    echo "\""
+                    echo '"'
                 fi
             done
         }
@@ -185,13 +185,13 @@ ensure_no_anaconda() {
     # tools. Make sure to exit it before doing anything with Homebrew.
     # It can also cause build issues for Atom packages with native modules.
 
-    if [[ -n "$CONDA_DEFAULT_ENV" ]]; then
+    if [[ -n $CONDA_DEFAULT_ENV ]]; then
         if command -v deactivate >/dev/null 2>&1; then
             run "source deactivate"
         fi
     fi
 
-    if [[ -n "$ANACONDA_ROOT" ]]; then
+    if [[ -n $ANACONDA_ROOT ]]; then
         PATH="$(echo "$PATH" | sed "s@$ANACONDA_ROOT/bin@@g;s@::@:@g;s@^:@@;s@:\$@@;")"
         MANPATH="$(echo "$PATH" | sed "s@$ANACONDA_ROOT/share/man@@g;s@::@:@g;s@^:@@;s@:\$@@;")"
         export PATH
@@ -204,7 +204,7 @@ ensure_no_anaconda() {
 in_array() {
     local e match="$1"
     shift
-    for e; do [[ "$e" == "$match" ]] && return 0; done
+    for e; do [[ $e == "$match" ]] && return 0; done
     return 1
 }
 
@@ -221,7 +221,7 @@ step_osx() {
 
     HOST="$(uname -n)"
     query "Set hostname [$HOST]" "$HOST"
-    if [[ -n "$REPLY" ]]; then
+    if [[ -n $REPLY ]]; then
         run "sudo scutil --set HostName '$REPLY'"
     fi
 
@@ -333,7 +333,7 @@ step_osx() {
         run "sudo chown -R root:wheel /Users/Shared/Background"
 
         MINOR_MACOS_VERSION="$(sw_vers | grep ProductVersion: | cut -f2 | cut -f2 -d.)"
-        if [[ "$MINOR_MACOS_VERSION" -ge 9 ]]; then
+        if [[ $MINOR_MACOS_VERSION -ge 9 ]]; then
             run "sqlite3 '$HOME/Library/Application Support/Dock/desktoppicture.db' 'delete from data;'"
             run "sqlite3 '$HOME/Library/Application Support/Dock/desktoppicture.db' 'insert into data values (\"$HOME/env/Rio.jpg\");'"
         else
@@ -743,7 +743,7 @@ step_osx() {
     run "defaults write com.apple.mail DisableReplyAnimations -bool true"
     run "defaults write com.apple.mail DisableSendAnimations -bool true"
 
-    show "Copy email addresses as \`foo@example.com\` instead of \`Foo Bar <foo@example.com>\` in Mail.app"
+    show 'Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app'
     run "defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false"
 
     show "Display emails in threaded mode, sorted by date (oldest at the top)"
@@ -1069,7 +1069,7 @@ step_brew() {
 
     if [[ -z "$(command -v brew)" ]]; then
         show "installing homebrew..."
-        run "ruby -e \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\""
+        run 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
         export PATH="$PATH:/usr/local/bin" # make sure brew is in your PATH before continuing
     else
         show "Homebrew already installed"
@@ -1108,8 +1108,8 @@ step_brew() {
         while IFS="" read -r line; do arr+=("$line"); done
         for I in $(brew ls); do
             name="${I%@*}"
-            [[ "$name" == "imagemagick" ]] && name="$name@6"
-            [[ "$name" == "pandoc-sidenote" ]] && name="jez/formulae/$name"
+            [[ $name == "imagemagick" ]] && name="$name@6"
+            [[ $name == "pandoc-sidenote" ]] && name="jez/formulae/$name"
             if ! in_array "$name" "${arr[@]}"; then
                 case "$I" in
                 "go") ;; # installed as a separate step
@@ -1165,7 +1165,7 @@ step_cask() {
     for I in $(brew cask list); do
         name="${I%@*}"
         if ! echo "$HOMEBREW_CASKS" | grep -Eq "$(echo "\\b$name\\b" | sed 's/ (!)//g')"; then
-            if [[ "$I" != "miniconda" ]]; then
+            if [[ $I != "miniconda" ]]; then
                 show -i "$I installed but not managed by setup via brew cask"
             fi
         fi
@@ -1281,7 +1281,7 @@ ensure_add_shell() {
     local BINARY="$1"
     local INSTALLED
     INSTALLED="$(grep "$BINARY" /etc/shells)"
-    if [[ "$INSTALLED" == "" ]]; then
+    if [[ $INSTALLED == "" ]]; then
         run "echo '$BINARY' | sudo tee -a /etc/shells"
     fi
 }
@@ -1343,7 +1343,7 @@ step_python() {
 
     if run "command -v conda >/dev/null 2>&1"; then
         MANAGE_WITH_ANACONDA=0
-        if [[ "$MANAGE_WITH_ANACONDA" == 1 ]]; then
+        if [[ $MANAGE_WITH_ANACONDA == 1 ]]; then
             # Allow anaconda to manage all the packages we've installed so that we're reasonably
             # sure that the installed versions will play nicely with each other.
             run "conda update --yes --prefix '$ANACONDA_DIR_NAME' conda"
@@ -1416,7 +1416,7 @@ ensure_rvm_ruby() {
         if [[ ! -e "$HOME/.rvm/scripts/rvm" ]]; then
             run "command curl -sSL https://rvm.io/mpapis.asc | gpg --import -"
             run "command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -"
-            run "\\curl -sSL https://get.rvm.io | bash -s stable --ruby" || abort "Failed to install rvm"
+            run '\curl -sSL https://get.rvm.io | bash -s stable --ruby' || abort "Failed to install rvm"
         fi
         if ! command -v rvm >/dev/null 2>&1; then
             # shellcheck source=.rvm/scripts/rvm
@@ -1518,7 +1518,7 @@ step_node() {
     IFS=$'\n'
     for I in $INSTALLED; do
         name="${I%@*}"
-        if [[ "$name" == "npm" ]]; then
+        if [[ $name == "npm" ]]; then
             continue
         fi
         if [[ $name == "UNMET-"* ]]; then
@@ -1572,7 +1572,7 @@ step_go() {
                 break
             fi
         done
-        if [[ "$FOUND" != "true" ]]; then
+        if [[ $FOUND != "true" ]]; then
             show -i "$install_name installed but not managed by setup via go get"
         fi
     done
@@ -1615,7 +1615,7 @@ step_cargo() {
                 break
             fi
         done
-        if [[ "$FOUND" != "true" ]]; then
+        if [[ $FOUND != "true" ]]; then
             show -i "$install_name installed but not managed by setup via cargo"
         fi
     done
@@ -1655,7 +1655,7 @@ step_env() {
 step_dotfiles() {
     run "cd '$HOME'"
     ROOT="$(git rev-parse --show-toplevel 2>&1)"
-    if [[ "$ROOT" != "$PWD" ]]; then
+    if [[ $ROOT != "$PWD" ]]; then
         echo run "git init" || abort "Please ensure git is installed"
         echo run "git remote add origin git@github.com:lexicalunit/dotfiles.git"
         echo run "git fetch origin master" || abort "Please ensure ssh access to github"
@@ -1675,11 +1675,11 @@ if [[ $(id -u) == 0 ]]; then
     exit 1
 fi
 
-if echo "$*" | grep -Eq -- "\\b--help\\b|\\b-h\\b"; then
+if echo "$*" | grep -Eq -- '\b--help\b|\b-h\b'; then
     usage
 fi
 
-if echo "$*" | grep -Eq -- "\\b--items\\b|\\b-i\\b"; then
+if echo "$*" | grep -Eq -- '\b--items\b|\b-i\b'; then
     IFS=' '
     for I in "${ITEM_LISTS[@]}"; do
         cleanup_item_list "$I"
@@ -1706,7 +1706,7 @@ shift $((OPTIND - 1))
 export SC_FORCE="$FORCE"
 export SC_DRYRUN="$DRYRUN"
 
-if [[ $LISTING == 0 && -z "$1" ]]; then
+if [[ $LISTING == 0 && -z $1 ]]; then
     usage
 fi
 
@@ -1718,17 +1718,17 @@ fi
 ARGS="$*"
 
 # update everything but osx
-if echo "$ARGS" | grep -Eq -- "\\bmost\\b"; then
+if echo "$ARGS" | grep -Eq -- '\bmost\b'; then
     ARGS="$ARGS apps dot"
 fi
 
 # update applications
-if echo "$ARGS" | grep -Eq -- "\\bapps\\b"; then
+if echo "$ARGS" | grep -Eq -- '\bapps\b'; then
     ARGS="$ARGS xcode java brew cask ext python node go cargo gem atom code"
 fi
 
 # update environment and dotfiles
-if echo "$ARGS" | grep -Eq -- "\\bdot\\b"; then
+if echo "$ARGS" | grep -Eq -- '\bdot\b'; then
     ARGS="$ARGS dotfiles zsh env"
 fi
 
@@ -1749,13 +1749,13 @@ steps=(
     "gem;           Upgrade/Install gem packages and rubygems-update package"
     "atom;          Ensure Atom installed via Homebrew Cask and apm packages are upgraded"
     "code;          Ensure VS Code installed via Homebrew Cask and its packages are installed"
-    "osx;           Override macOS \"defaults\" settings and configuration"
+    'osx;           Override macOS "defaults" settings and configuration'
 )
 
 LISTING_OUTPUT=""
 
 IFS=$'\n'
-(( steps_taken = 0 ))
+((steps_taken = 0))
 for step in "${steps[@]}"; do
     key="$(echo "$step" | cut -d';' -f1)"
     question="$(echo "$step" | cut -d';' -f2 | sed 's/^ *//g')"
@@ -1770,9 +1770,9 @@ for step in "${steps[@]}"; do
         continue
     fi
 
-    (( steps_taken = steps_taken + 1 ))
+    ((steps_taken = steps_taken + 1))
     ask "[$key] $question?"
-    if [[ "$REPLY" == "y" ]]; then
+    if [[ $REPLY == "y" ]]; then
         show "Beginning step [$key]"
         eval "$function"
     fi
