Updates shell script using shellfmt, updates settings, adds dogs.

diff --git a/bin/show_dircolors b/bin/show_dircolors
--- a/bin/show_dircolors
+++ b/bin/show_dircolors
@@ -4,14 +4,14 @@
 # Helps in creating a .dircolors color profile for ls by printing
 # out a directory containing a variety of different kinds of files.
 
-if echo "$*" | grep -Eq -- "\\b--help\\b|\\b-h\\b"; then
+if echo "$*" | grep -Eq -- '--help\b|-h\b'; then
     echo "usage: ${0##*/} [-h|--help]" 1>&2
     echo "Shows example output based on current dircolors settings." 1>&2
     exit 1
 fi
 
 if ! type gls >/dev/null 2>&1; then
-    echo "error: please \`brew install coreutils\` first." >&2
+    echo 'error: please `brew install coreutils` first.' >&2
     exit 1
 fi
 
