Makes usages output better.

diff --git a/bin/xdie b/bin/xdie
--- a/bin/xdie
+++ b/bin/xdie
@@ -2,32 +2,33 @@
 
 # Kills processes based on their window title.
 
-if [ "$1" = "-p" ]; then
+if [[ "$1" = "-p" ]]; then
 	PRETEND=1
 	shift
 fi
 
-if [ ! "$1" ]; then
-	echo "usage: $0 [-p] REGEX"
-	echo "kills all windows matching REGEX. -p enables pretend mode."
+if [[ -z "$*" || "$1" == "--help" || "$1" == "-h" ]]; then
+	echo "usage: $(basename "$0") [-p|-h|--help] REGEX"
+	echo "Kills all windows matching REGEX. Use -p for pretend mode."
 	exit 1
 fi
 
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
+
 LIST="$(xlsclients -l | egrep "^Window 0x([0-9]|[a-z])*:\$|^\W*Name:\W*.*\$" | sed 'N;s/:\n/ /g' | grep "$1")"
-if [ "$LIST" = "" ]; then
-	echo "no windows found"
+if [[ "$LIST" = "" ]]; then
+	show "no windows found"
 	exit 0
 fi
 
-echo "$(echo "$LIST" | wc -l) windows found:"
-echo "$LIST"
+show "$(echo "$LIST" | wc -l) windows found:"
+show "$LIST"
 
-if [ -z "$PRETEND" ]; then
-	echo -n "Killing windows... "
-	echo "LIST" | awk '{print $2}' | xargs -I{} xkill -id {}
+if [[ -z "$PRETEND" ]]; then
+	show "Killing windows... "
+	run "echo '$LIST' | awk '{print $2}' | xargs -I{} xkill -id {}"
 else
-	echo -n "Pretending to kill windows... "
-	echo "LIST" | awk '{print $2}' | xargs -I{} echo "xkill -id {}"
+	show "Pretending to kill windows... "
+	run "echo '$LIST' | awk '{print $2}' | xargs -I{} echo "xkill -id {}""
 fi
-echo "done"
-exit 0
+show "done"
diff --git a/bin/xf b/bin/xf
--- a/bin/xf
+++ b/bin/xf
@@ -3,40 +3,40 @@
 # Extract common file formats.
 
 # Display usage if no parameters given
-if [[ -z "$@" ]]; then
-  echo " ${0##*/} <archive> - extract common file formats)"
-  exit
+if [[ -z "$@" || "$1" == "--help" || "$1" == "-h" ]]; then
+    echo "usage: ${0##*/} <archive> - extract common file formats"
+    exit
 fi
 
 # Required program(s)
 # req_progs=(7z unrar unzip)
 req_progs=(unrar unzip)
 for p in ${req_progs[*]}; do
-  hash "$p" 2>&- || \
-  { echo >&2 " Required program \"$p\" not installed."; exit 1; }
+    hash "$p" 2>&- || \
+    { echo >&2 " Required program \"$p\" not installed."; exit 1; }
 done
 
 # Test if file exists
 if [ ! -f "$@" ]; then
-  echo "File $@ doesn't exist"
-  exit
+    echo "File $@ doesn't exist"
+    exit
 fi
 
 # Extract file by using extension as reference
 case "$@" in
-  # *.7z      ) 7z  x       "$@"                ;;
-  *.tar.bz2 ) tar xvjf    "$@"                ;;
-  *.bz2     ) bunzip2     "$@"                ;;
-  *.deb     ) ar  vx      "$@"                ;;
-  *.tar.gz  ) tar xvf     "$@"                ;;
-  *.gz      ) gunzip      "$@"                ;;
-  *.tar     ) tar xvf     "$@"                ;;
-  *.tbz2    ) tar xvjf    "$@"                ;;
-  *.tar.xz  ) tar xvf     "$@"                ;;
-  *.tgz     ) tar xvzf    "$@"                ;;
-  *.rar     ) unrar x     "$@"                ;;
-  # *.rar     ) 7z  x       "$@"                ;;
-  *.zip     ) unzip       "$@"                ;;
-  *.Z       ) uncompress  "$@"                ;;
-  *         ) echo " Unsupported file format" ;;
+    # *.7z      ) 7z  x       "$@"                ;;
+    *.tar.bz2 ) tar xvjf    "$@"                ;;
+    *.bz2     ) bunzip2     "$@"                ;;
+    *.deb     ) ar  vx      "$@"                ;;
+    *.tar.gz  ) tar xvf     "$@"                ;;
+    *.gz      ) gunzip      "$@"                ;;
+    *.tar     ) tar xvf     "$@"                ;;
+    *.tbz2    ) tar xvjf    "$@"                ;;
+    *.tar.xz  ) tar xvf     "$@"                ;;
+    *.tgz     ) tar xvzf    "$@"                ;;
+    *.rar     ) unrar x     "$@"                ;;
+    # *.rar     ) 7z  x       "$@"                ;;
+    *.zip     ) unzip       "$@"                ;;
+    *.Z       ) uncompress  "$@"                ;;
+    *         ) echo " Unsupported file format" ;;
 esac
