Adds `dev` command to `.profile_docker`.

diff --git a/env/dot_profile_docker b/env/dot_profile_docker
--- a/env/dot_profile_docker
+++ b/env/dot_profile_docker
@@ -1,5 +1,94 @@
 #! .profile_docker
 
+# shellcheck source=.shell_control
+source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2
+
+# Docker Aliases
+alias dc="docker-compose"
+alias dm="docker-machine"
+alias de="eval \"\`docker-machine env dev\`\""
+
+# Local Development Tools
+_ensure_docker_env() {
+    [[ -n $DOCKER_HOST ]] && return 0
+    run 'eval "`docker-machine env dev`"'
+    if [[ -z $DOCKER_HOST ]]; then
+        _err "docker vm is not running"
+        return 1
+    fi
+}
+
+dev() {
+    op=$1
+    [[ -z $1 ]] || shift
+    case "$op" in
+        init)       _dev_init "$@";;
+        pull)       _dev_pull "$@";;
+        stop)       _dev_stop "$@";;
+        clean)      _dev_clean "$@";;
+        *)          _err "unknown dev option. Options: init, pull, stop, clean";;
+    esac
+}
+
+_dev_init() {
+    run "docker-machine start dev" && run "eval \"$(docker-machine env dev)\""
+    if [[ "$?" -ne "0" ]]; then
+        grep "$(docker-machine ip dev)" /etc/hosts >/dev/null 2>&1
+        if [[ "$?" -ne "0" ]]; then
+            show -i "Please add \"$(docker-machine ip dev)\tdev\" to /etc/hosts"
+            run "sudo $EDITOR /etc/hosts"
+        fi
+    fi
+}
+
+_dev_pull() {
+    _ensure_docker_env || return 1
+    for image in $(grep image docker-compose.yml | awk '{print $2}' | sort | uniq ); do
+        run "docker pull $image | grep 'Status\|fs layer'"
+        if [ "$?" -ne "0" ]; then
+            failure="$failure $image"
+        fi
+    done
+}
+
+_dev_stop() {
+    run "docker-machine stop dev"
+}
+
+_dev_clean() {
+    _ensure_docker_env || return 1
+    run "docker ps -aq | xargs docker kill"
+    run "docker ps -aq | xargs docker rm"
+    if [[ "$1" == "images" ]]; then # optionally remove old images
+        run "docker images -aq -f dangling=true | xargs docker rmi --force"
+        DOCKER_VERSION="$(docker --version | sed 's/Docker version //g;s/,.*//g')"
+        MAJOR="$(echo $DOCKER_VERSION | cut -d. -f1)"
+        MINOR="$(echo $DOCKER_VERSION | cut -d. -f2)"
+        if [[ $MAJOR -gt 1 ]] || [[ $MAJOR -eq 1 && $MINOR -ge 9 ]]; then
+            run "docker volume ls -qf dangling=true | xargs docker volume rm"
+        else
+            show -i "docker version less than 1.9, can not clean up dangling any dangling volumes"
+        fi
+    fi
+}
+
+# Shell Completions
+
+_dev() {
+    if type emulate 1>/dev/null 2>&1; then
+        emulate -L ksh
+    fi
+    local cur="${COMP_WORDS[COMP_CWORD]}"
+    local prev="${COMP_WORDS[COMP_CWORD-1]}"
+    COMPREPLY=()
+    if [[ -z "$prev" || $COMP_CWORD == 1 ]]; then
+        local opts=("init" "pull" "stop" "clean" "migrate")
+        COMPREPLY=($(compgen -W "$(echo -n "${opts[@]}")" -- "${cur}"))
+        return 0
+    fi
+} &&
+complete -o default -F _dev dev
+
 # prefix docker ps with ips
 function docker-ips() {
     docker ps | while read line; do
@@ -18,7 +107,7 @@ function docker-clean-exited() {
         echo $line | grep '^CONTAINER ID' && continue;
         CID=$(echo $line | awk '{print $1}');
         docker inspect -f "{{ .State.Running }}" $CID | grep -q 'false' && docker rm -f $CID;
-        
+
     done;
 }
 
